apiVersion:  v1
kind: Route
metadata:
  name: app-z
  namespace: petclinic
  labels:
    app: app-z
spec:
  rules:
    - http:
       paths:
         - path:
           backend:
             serviceName: app-z
             servicePort: 8080
