jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy: "loggedInUsersCanDoAnything"
  disableRememberMe: false
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: false
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        password: ${jenkins_password:-xebialabs}
tool:
  dockerTool:
    installations:
    - name: "docker"
      properties:
      - installSource:
          installers:
          - docker:
              version: "latest"
  git:
    installations:
    - home: "git"
      name: "Default"
  maven:
    installations:
    - name: "maven3"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.5.0"
jobs:
  - script: >
      pipelineJob('petclinic-demo') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/dbroker13/spring-petclinic.git')
                }
                branch('*/main')
              }
            }
            lightweight()
          }
        }
      }

credentials:
  system:
    domainCredentials:
      - credentials:
        - usernamePassword:
            scope:    GLOBAL
            id:       cred
            username: $DOCKER_HUB_USER
            password: $DOCKER_HUB_PASS
        - usernamePassword:
            scope:    GLOBAL
            id:       xld
            username: admin
            password: admin
        - usernamePassword:
            scope:    GLOBAL
            id:       xlr
            username: admin
            password: admin
