---
apiVersion: xl-release/v1
kind: Templates
spec:
- directory: container-demo
  children:
  - name: deploy
    type: xldeploy.XLDeployServer
    url: http://xld:4516
    username: admin
    password: admin
  - name: jenkins
    type: jenkins.Server
    url: http://jenkins:8080
    username: admin
    password: admin
  - template: container release
    scheduledStartDate: 2021-02-26T12:45:40.180Z
    dueDate: 2021-02-26T13:45:40.181Z
    phases:
    - phase: Build
      tasks:
      - name: build image and publish
        type: jenkins.Build
        jenkinsServer: jenkins
        jobName: petclinic-demo
        variableMapping:
          pythonScript.buildNumber: ${buildnumber}
      color: '#0079BC'
    - phase: Deploy to Openshift
      tasks:
      - name: Generate Namespace
        type: xldeploy.Deploy
        server: deploy
        deploymentApplication: Applications/container-demo
        deploymentPackage: Applications/container-demo/${buildnumber}
        deploymentEnvironment: Environments/test/openshift
      - name: Perform Container Deployment
        type: xldeploy.Deploy
        server: deploy
        deploymentApplication: Applications/container-demo
        deploymentPackage: Applications/container-demo/${buildnumber}
        deploymentEnvironment: Environments/test/openshift
      color: '#0079BC'
    - phase: Verify
      tasks:
      - name: Verify Application
        type: xlrelease.Task
        owner: admin
      color: '#0079BC'
    - phase: Destroy Openshift
      tasks:
      - name: Destroy Deployment
        type: xldeploy.Undeploy
        server: deploy
        deployedApplication: Environments/test/openshift
      color: '#0079BC'
    variables:
    - type: xlrelease.StringVariable
      key: buildnumber
      showOnReleaseStart: false
    riskProfile: Default risk profile
